stages:
  - test
  - validate
  - plan
  - deploy

variables:
  TF_ROOT: "infra/terraform/environments/dev"
  TF_STATE_NAME: "incidentops-dev"

  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

  AWS_REGION: "eu-west-1"
  AWS_DEFAULT_REGION: "eu-west-1"

  # Backend HTTP GitLab
  TF_HTTP_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}"
  TF_HTTP_LOCK_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock"
  TF_HTTP_UNLOCK_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock"
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: "${CI_JOB_TOKEN}"
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: "5"

# Configuration commune pour les jobs qui doivent accéder à AWS.
.aws_oidc:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com

  before_script:
    - test -n "$AWS_ROLE_ARN" || (echo "AWS_ROLE_ARN is missing" && exit 1)
    - test -n "$GITLAB_OIDC_TOKEN" || (echo "GITLAB_OIDC_TOKEN is missing" && exit 1)
    - printf '%s' "$GITLAB_OIDC_TOKEN" > /tmp/gitlab-oidc-token
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/gitlab-oidc-token
    - export AWS_ROLE_SESSION_NAME="GitLab-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"

python:test:
  stage: test
  image: python:3.12-slim

  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements-dev.txt

  script:
    - python -m py_compile src/api/handler.py
    - python -m pytest -v

terraform:fmt:
  stage: validate
  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]

  script:
    - terraform -chdir="$TF_ROOT" fmt -check

terraform:validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]

  script:
    - terraform -chdir="$TF_ROOT" init -backend=false
    - terraform -chdir="$TF_ROOT" validate

terraform:plan:
  extends: .aws_oidc
  stage: plan

  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]

  rules:
    - when: manual

  script:
    - terraform -chdir="$TF_ROOT" init -reconfigure
    - terraform -chdir="$TF_ROOT" plan -out=tfplan
    - terraform -chdir="$TF_ROOT" show -no-color tfplan > "$TF_ROOT/tfplan.txt"

  artifacts:
    paths:
      - "$TF_ROOT/tfplan"
      - "$TF_ROOT/tfplan.txt"
    expire_in: 1 day

terraform:apply:
  extends: .aws_oidc
  stage: deploy

  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]

  needs:
    - job: terraform:plan
      artifacts: true

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - when: never

  script:
    - terraform -chdir="$TF_ROOT" init -reconfigure
    - terraform -chdir="$TF_ROOT" apply -auto-approve tfplan